version: '3'
services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    networks:
      - keycloak-network

  spring-boot-app:
    build: .
    depends_on:
      - keycloak
    ports:
      - "8081:8081"
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/auth/realms/proxym
      # Other Keycloak configurations here
    networks:
      - keycloak-network

networks:
  keycloak-network:
